version: '3.8'

volumes:
  leo_getz_postgres:
    external: true

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - leo_getz_postgres:/var/lib/postgresql/data/
  bot:
    build:
      context: ""
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - STATIC_ROOT=/code/app/static/
      - MEDIA_ROOT=/code/app/media/
    command:
      - '/code/bin/wait-for-it'
      - 'postgres:5432'
      - '--'
      - 'python'
      - '/code/app/manage.py'
      - 'runserver'
      - '0.0.0.0:8053'
    volumes:
      - .:/code
    ports:
      - "8053:8053"
    depends_on:
      - postgres
