# Generated by Django 3.1.2 on 2020-10-24 02:09

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object should be treated as active.Unselect this instead of deleting objects.', verbose_name='active')),
                ('created_at', pgcrypto.fields.DateTimePGPSymmetricKeyField(auto_now_add=True)),
                ('modified_at', pgcrypto.fields.DateTimePGPSymmetricKeyField(auto_now=True)),
                ('movie_title', pgcrypto.fields.CharPGPSymmetricKeyField(db_index=True, help_text='The title of the movie.', max_length=255)),
                ('movie_url', pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, db_index=True, help_text='The URL for the movie.', max_length=255, null=True)),
                ('fulfilled', models.BooleanField(default=False, help_text='True if this request is fulfilled.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movierequests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie_requests',
                'ordering': (builtins.id,),
                'default_permissions': (),
            },
        ),
    ]
