# Generated by Django 3.1.2 on 2020-10-30 04:20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlexMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this object should be treated as active.Unselect this instead of deleting objects.', verbose_name='active')),
                ('plex_guid', models.CharField(help_text='Plex GUID.', max_length=512)),
                ('title', models.CharField(help_text='The title of the movie.', max_length=255)),
                ('year', models.SmallIntegerField(db_index=True, help_text='The year the movie was released.')),
                ('duration', models.BigIntegerField(help_text='The duration of the movie in milliseconds.')),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('directors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('producers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('writers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'plex_movies',
                'ordering': ('id',),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='movierequest',
            options={'default_permissions': (), 'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='movierequest',
            name='movie',
            field=models.ForeignKey(help_text='The movie on the Plex server that fulfilled this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_requests', to='movie_requests.plexmovie'),
        ),
    ]
