# Generated by Django 4.1.4 on 2023-02-04 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_requests', '0003_auto_20201030_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierequest',
            name='tmdb_id',
            field=models.IntegerField(default=0, help_text='The ID of the movie from themoviedb.org. This is the part that comes after the slash.', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movierequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
