# Generated by Django 4.1.4 on 2023-02-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_requests', '0004_movierequest_tmdb_id_alter_movierequest_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierequest',
            name='tmdb_id',
            field=models.IntegerField(help_text='The ID of the movie from themoviedb.org. This is the part that comes after the slash.'),
        ),
        migrations.AlterUniqueTogether(
            name='movierequest',
            unique_together={('tmdb_id', 'fulfilled')},
        ),
    ]
