# Generated by Django 3.1.2 on 2020-10-24 03:36

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201023_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=pgcrypto.fields.CharPGPSymmetricKeyField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
